<?php
// all bad will give ERROR
get_bloginfo('home');
get_bloginfo('url');
get_bloginfo('wpurl');
get_bloginfo('stylesheet_directory');
get_bloginfo('template_url');
get_bloginfo('text_direction');
get_bloginfo('feed_url');
bloginfo('home');
bloginfo('url');
bloginfo('wpurl');
bloginfo('stylesheet_directory');
bloginfo('template_url');
bloginfo('text_direction');
bloginfo('feed_url');
get_option('home');
get_option('site_url');
