
<p>Lubith</p>
<!-- saved from url=(0045)http://docs.pinegrow.com/editing/code-editing -->
<?php
/**
 * This theme was generated with Lubith - The Wordpress Theme Generator: http://www.lubith.com
 */
$shortname = "artisteer";
function themler_shortcode_login_link() {}
/**
* @package templatetoaster
*/
/* funcion que verifica si el dominio es wpthemegenerator */
function is_wpthemegenerator(){
	if( $_SERVER['HTTP_HOST'] === 'www.wpthemegenerator.com' ){
		return true;
	} else {
		return false;
	}
}
/*
 * Resource files included by Pinegrow.
 */

// OK.

/*
 * Pine tress grow everywhere.
 */

/**
 * This theme template was built in a toaster by artists
 */

function wp_vs_them() {}
