remove_section( "themes" )
remove_section( 'themes' )
remove_section("themes")
remove_section('themes')
remove_control( "active_theme" )
remove_control( 'active_theme' )
remove_control("active_theme")
remove_control('active_theme')

$wp_customize->remove_section( 'themes' );
$wp_customize->remove_control( 'active_theme' );

$wp_customize->remove_section( 'theme_options' );
$wp_customize->remove_section( 'colors' );